// <auto-generated />
namespace RAM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SeedMovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedMovies));
        
        string IMigrationMetadata.Id
        {
            get { return "201709150425259_SeedMovies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
